---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/asciidoctor-plantuml.rb

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200
  Exclude:
    - test/test_plantuml.rb

Metrics/AbcSize:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/LineLength:
  Max: 120
